app:
  name: xrf1

log:
  level: INFO
  suffix: log
  prefix: xrf1
  output: .logs

database:
  postgres:
    port: 5432
    host: "127.0.0.1"
    name: "xrf1assets"
    username: "postgres"
    password: "password"

server:
  grpc:
    port: 50051
  http:
    port: 8010
    host: 127.0.0.1
